// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PixelV0.Infrastructure.Data;

#nullable disable

namespace PixelV0.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423154709_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PixelV0.Modules.Catalog.Entity.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Game_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalog", "catalog");
                });

            modelBuilder.Entity("PixelV0.Modules.Identity.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Like", b =>
                {
                    b.Property<Guid>("User_ID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Post_ID")
                        .HasColumnType("uuid");

                    b.HasKey("User_ID", "Post_ID");

                    b.HasIndex("Post_ID");

                    b.ToTable("Likes", "social");
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Game_ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Image_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Preset_ID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User_ID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Game_ID");

                    b.HasIndex("Preset_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Posts", "social");
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Game_ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("User_ID")
                        .HasColumnType("uuid");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Game_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Presets", "social");
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Like", b =>
                {
                    b.HasOne("PixelV0.Modules.Social.Entity.Post", null)
                        .WithMany()
                        .HasForeignKey("Post_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PixelV0.Modules.Identity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Post", b =>
                {
                    b.HasOne("PixelV0.Modules.Catalog.Entity.Catalog", null)
                        .WithMany()
                        .HasForeignKey("Game_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PixelV0.Modules.Social.Entity.Preset", null)
                        .WithMany()
                        .HasForeignKey("Preset_ID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("PixelV0.Modules.Identity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PixelV0.Modules.Social.Entity.Preset", b =>
                {
                    b.HasOne("PixelV0.Modules.Catalog.Entity.Catalog", null)
                        .WithMany()
                        .HasForeignKey("Game_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PixelV0.Modules.Identity.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
